import Head from 'next/head';
import MainLayout from '../components/layout/MainLayout';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Learnr | A community for Learnr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        Home Page
      </MainLayout>
    </div>
  );
}
